### ISSUE TITLE
Feature to disable/prevent popover from opening

### ISSUE THREAD

**Issue by 6matko** [material-extended/mde#12]
#### Bug, feature request, or proposal:
Feature request.

#### What is the expected behaviour?
Expected to disable popover from showing based on some conditions, for example, if editing is disabled.
**[mdePopoverDisabled]="true/false"**

#### What is the current behaviour?
Currently I am using **onPopoverOpen** method to pass some data from view like this:
```
<div *ngFor="let item of items"">
<div [mdePopoverTriggerFor]="itemPopover" mdePopoverPositionX="after" mdePopoverPositionY="above" [mdePopoverArrowWidth]="12"
                [mdePopoverEnterDelay]="200" [mdePopoverOverlapTrigger]="false"
 (onPopoverOpen)="showDetails(item)">{{item.name}}</div>
</div>
```
In some cases I don't want popover to be shown, for example, when edit mode is disabled. To achieve my goal I use very ugly and _blinking_ hack:
```
showDetails(item: Item) {
    if (!this.editMode) {
        this.trigger.closePopover();
    }
    ...
}
```

#### What are the steps to reproduce?

Provide a working example using StackBlitz (or similar) to reproduce the problem.
StackBlitz Template: https://stackblitz.com/fork/mde-popover

#### What is the use-case or motivation for changing an existing behaviour?
There might be some cases where popover must be disabled (not shown) on click or hover, but in other cases it should be fully functional based on some conditions.

**Comment by joejordanbrown** [comment]
@6matko 

Thanks for the feature request. 

I agree this should be added ASAP. I can see so many use cases for this. I think it should also work using `[disabled]` to work with the native disabled attribute. This would then work with the button disabled etc. 

Do you think that sound reasonable?

**Comment by 6matko** [comment]
Yes, it would be really reasonable. In my current case I don't use button, so ```[disabled]``` property might not work, but in button cases it would be great solution. Additionally in my personal case I run into a problem with arrow (I don't need an arrow). Maybe similar feature can be added also to disable arrow, for example, arrowWidth = 0?

**Comment by joejordanbrown** [comment]
@6matko 

I will add that today, I've just seen that the latest `@angular/cdk` was released last night so I will upgrade for compatibility with that too. So this feature will only work with the latest `@angular/cdk`, I hope that won't be a problem.

If you want disabled like features on custom elements you need to add accessibility attributes and the correct styles yourself to accomplish the same effect as native elements. I will leave that to the developers, I can add examples of the correct accessibility setup to use on none native elements. 

Hmm I will look into that, I remember that you can use the `[mdePopoverOverlapTrigger]` which actually by default is set to true and then you use offset if you want it to offset. What happens when you use arrow width 0? I can't remember but in theory that should work unless it has a problem with the math part when using that, I would need to test that to see what the problem is.

If `[arrowWidth]="0" doesn't work then please create an issue with an example using StackBlitz and I will look into that once I've published it to work with the latest CDK.

**Comment by joejordanbrown** [comment]
@6matko 

I just had a think about this and how disabled works on other elements, it just uses CSS `pointer-events: none;` I'm not sure if this should actually be added to the logic and instead if you apply the attribute `[disabled]` and have the following CSS it will be disabled.

**CSS**
```css
[disabled] {
  pointer-events: none;
}

/*
 * This prevents it from being disabled when it has the disabled attribute with a value of false.
 */
[disabled="false"] {
  pointer-events: initial;
}
```

**HTML**
```html
<div [mdePopoverTriggerFor]="appPopover"
     tabindex="0"
     role="button"
     [disabled]="false">Hover Popover</div>
```

I've also added the correct accessibility attributes to the trigger element. Let me know how you get on using that method. I will add to documentation soon.

**Comment by 6matko** [comment]
@joejordanbrown Yes, the disabled property is working and fits my current use case, thank you! :)
I will play around with ```[arrowWidth]="0"``` more and if it wont help create a new issue, as you said.
